# Generated by Django 5.2.15 on 2026-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
