# Generated by Django 5.2.15 on 2026-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch_no',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
